name: 'ValetParker'
pygments: false
markdown: kramdown
paginate: 10
version: 1.0

seo:
  author: 'Charlie Gourlis'
  description: ''
  keywords: ''

url:
permalink: /:year/:title

google:
  analytics : ''

assets:
  img: '/assets/images/'
  css: '/assets/stylesheets/'
  js: '/assets/javascripts/'
